### ISSUE TITLE
Homepage is down

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#110]
Our homepage is down (http://tunics.legofarmen.se). We should fix that.

**Comment by christopho** [comment]
Is your project still active?

**Comment by mattias-p** [comment]
Not really. I'd like to get back to Tunics some day. I have this itch generate more interesting mazes but right now I'm lacking inspiration.

**Comment by sandstrand** [comment]
I've dug deep and found a complete dump of the website. 

I am however considering moving all information about contribution and development to a github wiki for the repository and create another simplified front page for the result of the project.  

@mattias-p  Sound good?

**Comment by mattias-p** [comment]
Sounds great!!

**Comment by sandstrand** [comment]
- [x] Transfer documentation on development and contribution to github wiki
- [x] Create and publish new public website.

**Comment by sandstrand** [comment]
Documentation is moved to repository wiki.
New website at https://tunics.legofarmen.se
