### ISSUE TITLE
Wrong genre

### ISSUE THREAD

**Issue by Wuzzy2** [Legofarmen/tunics#111]
Please review the definition of “roguelike”. This game is not a roguelike. This looks more like an action game or hack-and-slay game. (This is not a bad thing, I'm just saying the genre description is wrong.)

Just because a game is randomly generated and has permadeath does not make it a roguelike. By that logic, even space shooters could be roguelikes by including these mechanics. All roguelike games are first and foremost turn-based games, giving infinite time to think and are strictly tile-based (including for player positions). This is not the case here.

http://www.roguebasin.com/

Examples of roguelike games:

- Dungeon Crawl Stone Soup
- Cataclysm: Dark Days Ahead
- NetHack

Counter-examples:

- Spelunky (action platformer) (yes, they abuse the term “roguelike”, too)
- Hardcore Mode in Minecraft (sandbox)
- Tunics! (hack-and-slay)

**Comment by mattias-p** [comment]
First of all I'm excited that you've taken enough interest in our game to provide this critique! :D

I'm in full agreement with you that Tunics! is not a roguelike. In fact we claim it's a roguelike-like, which I think is quite fitting. See [Wikipedia](https://en.wikipedia.org/wiki/Roguelike#Roguelike-likes_and_procedural_death_labyrinths) and [Roguebasin](http://www.roguebasin.com/index.php?title=Roguelike-like) for "definitions".

**Comment by Wuzzy2** [comment]
Heh. Roguelike-like sounds funny. :D

**Comment by mattias-p** [comment]
Yeah, I like it. It'll also eat your shield :)
