### ISSUE TITLE
Floor alignment of flippers obstacles

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#13]
The component design guidelines states that water tiles and frames should align the to the grid when possible.

Some flippers obstacles are needlessly misaligned.

All flippers obstacles must be aligned to the grid.

**Comment by sandstrand** [comment]
This cannot be achieved on all obstacle_flippers. More specifically, any moat originating from a wall and does not reach the opposing wall, cannot align to the grid. Instead, barriers can be added instead of jumpers to achieve this.

**Comment by sandstrand** [comment]
Partially fixed and merged.

Moving issue to milestone where layers and floors are reworked.

**Comment by mattias-p** [comment]
@sandstrand I believe this was fixed already in 0.2. If you don't have anything else, this could be closed.
