### ISSUE TITLE
Ambigous language about alignment

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#14]
The component design guidelines uses the term "grid" to describe how entities should align to the floor tiles.

The quest_editor grid and the standard floor tile alignment are displaced from eachother 8px in each axis. Which may be a cause for confusion.

The language regarding alignment in the component design guidelines must be unambigous.

**Comment by sandstrand** [comment]
Clarified grid in http://z.legofarmen.se/component_design_guidelines#floor_grid_alignment_and_margins
