### ISSUE TITLE
Falling sound when flying enemies die over holes.

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#15]
Bari can fly over holes.

When a red bari is killed above a hole, a falling sound is played before it splits into mini-baris.

No falling sound should be played when a bari is split into mini-baris.

**Comment by sandstrand** [comment]
The standard standard enemy_killed sound should play when ta red bari is killed and split.

**Comment by sandstrand** [comment]
This behavior is common with all flying monsters. This is an issue with the core enemy type behavior.

Can obstacle_behavior be modded or is this an issue for Solarus core?

**Comment by christopho** [comment]
This is a Solarus issue, fixed in 1.4.4.

**Comment by mattias-p** [comment]
Verified fixed with Solarus 1.4.5.

**Comment by mattias-p** [comment]
Was fixed by #79.
