### ISSUE TITLE
Enemies get their arms and legs stuck in chests

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#27]
Sometimes when you press a switch a chest materializes from nowhere.

If an enemy happens to be in the wrong place at the wrong time, it gets stuck in the chest and can't move away.

When a chest materializes inside an enemy it must push the enemy away or possibly kill it.

**Comment by sandstrand** [comment]
An evaluation should be performed push the enemy 16px in each direction (NESW) and if it fails kill it.

**Comment by mattias-p** [comment]
I like your suggested approach. However I think a better distance to move would be max(chest.size, enemy.size) / 2.

To make this work I believe we need a new [feature](https://github.com/christopho/solarus/issues/898) in Solarus.

**Comment by mattias-p** [comment]
Use the dungeon with seed = 1468146045 tier = 1 and walk north twice. 
The room you should find is obstacle_puzzle_nsew_000777_2. Fill it with enemies for a better debugging experience. (For the record I'm using Solarus 1.4)

**Comment by mattias-p** [comment]
I've got a WIP branch in my repo: https://github.com/mattias-p/tunics/tree/stuck
