### ISSUE TITLE
Synchronized snapdragon jumping

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#28]
Enemies often show up several of a kind in a room.

When you enter a room with more than one snapdragon they all jump to a common beat until you start beating them and they drop out of sync.

Snapdragons timings should employ enough randomness to make them seem a pack of wild animals rather than a cheerleading squad in oddball costumes.

**Comment by sandstrand** [comment]
Time spent jumping is defined by the sprite's jumping animation timing. Until we separate enemies from their shadows, this cannot be changed.

The delay and animation between jumps follow the lttp pattern closely, but could be tweaked to achieve more randomness.

**Comment by mattias-p** [comment]
The timing between individual jumps isn't the problem. It's that they all pause and resume at the same time.

**Comment by sandstrand** [comment]
Yes, and the pause between sets of jumps and the number of jumps in a set is what can be altered as of now.

**Comment by sandstrand** [comment]
Fixed by #44
