### ISSUE TITLE
Install and running

### ISSUE THREAD

**Issue by washu-chan** [Legofarmen/tunics#3]
Hello =)
All right, I am aware that many people who get this game from github probably know their ways around github-projects and are used to fetching both this and that, but it could be good to add some specifications for us dummies.
First, Solarus: Very good with a link there, love it. However, point out that what the user is looking for is the folder corresponding to their own OS, I spent some time getting confused staring at the solarus developement source-installation before I had to ask 'ehm, do I really need to install all this and compile it?', and then realized that I got the wrong package. Just a thought there, Mac -> macosx, Win -> win32.

Second, running the game!
I have a suggestion that you make some dummy-version here too, one for linux, which basically seems to be there already, one for windows-users and one for mac-users.
Since it said 'Thus, to run tunics ... , you can type', I personally thought 'Aha, so you have to start this one from the command-prompt..'. Which apparantly was not Quite true, you Can, but you do not Have to.
So, it would have been good to write something like "download the game, unzip and then copy the 'data' folder and place it inside your solarus-folder, then press 'solarus.exe'. Enjoy!"
Since, that seems like what you basically have to do in Windows.

With easy to follow instructions, the more people will be able to try this game out =)

**Comment by sandstrand** [comment]
There is certainly room for improvements in the readme regarding installation on windows and mac.  

Keep in mind that this is the development repository for the game. Once we reach our first named release, which should be very shortly, we will start distributing the game packaged with Solarus for an easy unzip-and-play installation.

**Comment by sandstrand** [comment]
Documentation should be separated for those who clone and install from github and those who download a full distribution with Solarus.

**Comment by Tjompalompa** [comment]
So these are the somewhat complicated instructions for running tunics on mac:
1. Clone the tunics repository.
2. Download the latest Solarus 1.3.x package from http://www.solarus-games.org/downloads/solarus/macosx/
3. Copy the ”data” directory from the tunics repository.
4. In the Solarus package, open the solars_bundle directory to find Solarus.app
5. Right click on Solarus.app and click ”show contents of package”.
6. Find the directory ”Resources” in ”Contents”. Paste ”data” into the ”Resources" directory.
7. Run ”solarus” in the same directory to start the game.
8. For reasons at the moment unknown, you can not start tunics by simply running Solarus.app, instead you always need to run ”solarus” in ”Resources”. You can, however create an alias(shortcut) directly to ”solarus”.

Feel free to shorten or clarify.
