### ISSUE TITLE
Migrate to Solarus 1.4

### ISSUE THREAD

**Issue by sandstrand** [Legofarmen/tunics#32]
Evaluate and plan migration to Solarus 1.4

**Comment by sandstrand** [comment]
Resolves #15 if 1.4.4.

**Comment by mattias-p** [comment]
- [x] [Produce working code](https://github.com/mattias-p/tunics/tree/solarus1.4)
- [x] Update README.md
- [ ] Acceptance testing
  - [ ] Installation instruction for Windows
  - [ ] Installation instruction for OSX
  - [ ] Installation instruction for Ubuntu
  - [ ] Playtest

What else?

**Comment by ekureina** [comment]
Solarus 1.4 version of Tunics seems to work from @mattias-p's repository.

**Comment by sandstrand** [comment]
Ran into problems testing the installation for 1.4.5. Reported:
http://forum.solarus-games.org/index.php/topic,691.0.html 
Bundle does not behave as previous versions such as 1.4.4
