### ISSUE TITLE
Being pushed out of ambush rooms

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#5]
When our hero enters an ambush room he is sucked into the room and the door closes behind him.

If our hero is hurt before the door is closed, he is pushed back into the doorway with the door still open. If he tries to walk away he is sucked back into the room again in a rather surprising fashion.

Our hero must not be hurt while he is being sucked into an ambush room.

**Comment by sandstrand** [comment]
If the sensor that triggers the movement also triggers hero:set_invincible() this should be resolved.

**Comment by mattias-p** [comment]
Yeah, and then another call when once the door is closed.

I'm trying out an [issue, pull-request, review, merge] development process to see how it fits. Add milestones if you like.

**Comment by mattias-p** [comment]
Please review.
