### ISSUE TITLE
Unlimited heart containers in a single tier

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#6]
When a game restored from disk, the hero starts out at the entrance of the current tier.

It is possible to beat Agahnim and get his heart container an unlimited number of times before going to the next tier by saving and restoring the game after picking up the heart container, but before walking up the stairs.

Agahnim must not be resurrected when restoring the game.

**Comment by mattias-p** [comment]
What's the point of having Agahnim escape instead of dying?

**Comment by sandstrand** [comment]
I think the Idea was to chase him through the tiers and kill him on the final one. Never implemented.

**Comment by mattias-p** [comment]
Ok. I'll remove the escape mechanism. It's not like he can't be respawned after each tier.
Then I'll add a savegame variable to him so the map ignores him if he's dead. The savegame variable will be cleaned up between tiers.

**Comment by mattias-p** [comment]
Please review.
