### ISSUE TITLE
Debug info screen

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#69]
##### BACKGROUND

When you spot a bug and want to reproduce it, you want to find out the seed and tier numbers used to generate the current dungeon.
##### CURRENT SITUATION

You have to save and quit, locate and open the save game file and locate the rows where the seed and tier numbers are written.
##### REQUIREMENT

There must be a debug info screen accessible from the pause menu. The debug info screen must shows the seed and tier numbers used for the current dungeon.

**Comment by sandstrand** [comment]
Preferably this information should be displayed in the lower left corner of the screen while in map or inventory menus. Should we add tunics version and solarus version to the debug information?

![seed](https://cloud.githubusercontent.com/assets/11724954/9784187/f9798dee-57a9-11e5-8a99-0aa2883b7e7f.PNG)
