### ISSUE TITLE
Stuck in a room after saving

### ISSUE THREAD

**Issue by christopho** [Legofarmen/tunics#74]
I saved and quit after opening a door in such a room:

![tunics-door-bug](https://cloud.githubusercontent.com/assets/411718/9944946/b8a6716a-5d8a-11e5-8817-5b1d0cdbc257.png)

When I resume the saved game and go to that room again, the door gets closed and I cannot trigger the switch, it is already on.

I am playing with git tag v0.1 and Solarus 1.3.1.

**Comment by mattias-p** [comment]
I fail to reproduce this. I found two seeds (5 and 9) with trap rooms immediately to the west of the starting room on tier 1, but I can't get either one to exhibit the described behavior.

I use this settings file to force a specific seed for new games (and enable some debug friendliness):

```
$ cat $HOME/.solarus/tunics/settings.dat
quest_seed = 5
quest_tier = 1
debug_cheat = true
debug_walking_speed = 176
quest_sword_ability = 2
skip_cinematics = true
```

If you (or anyone else) can provide a seed and tier with a malfunctioning door, that'd be great! Both values are written out in clear text in the save file:

```
$ egrep "seed|tier" $HOME/.solarus/tunics/save.dat
seed = 5
tier = 1
```

**Comment by christopho** [comment]
Ok, you can close it, I will tell you and give the seed if I reproduce it again.

**Comment by mattias-p** [comment]
Great, thanks!
