### ISSUE TITLE
add-apt-repository not found

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#75]
The Ubuntu installation instruction prescribes using `add-apt-repository` (from the `software-properties-common` package) which isn't installed as part of the base system.

```
$ sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
sudo: add-apt-repository: command not found
```

 A workaround suggested elsewhere is to [add the repository to /etc/apt/sources.list manually](http://ubuntuforums.org/showthread.php?t=1320536). This command should do the trick in most cases: `echo "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe" | sudo tee -a /etc/apt/sources.list`.

**Comment by sandstrand** [comment]
Tested enough to be closed?

**Comment by sandstrand** [comment]
No longer an issue.
