### ISSUE TITLE
Flying enemies can't fly over "low" obstacles

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#77]
Flying enemies should be able to fly over "low" obstacles like barriers.

**Comment by sandstrand** [comment]
Possible causes and solutions:
- Wrong obstacle type for tile > Update tilesets
- Wrong behaviour type for enemy > Update Enemy code
- Core issue > Feature request for fixed obstacle type or added obstacle type.

**Comment by christopho** [comment]
Entities of ground "low_wall" can be traversed by flying enemies in the engine, I confirm it. By flying, I mean enemy:set_obstacle_behavior("flying").

**Comment by sandstrand** [comment]
Thanks, I'll check the code.

**Comment by mattias-p** [comment]
I've got a fix for this on the solarus1.4 branch of my own fork here at Github. Since I created it using the 1.4 quest editor we might want to merge the migration first, in case the editor broke something for 1.3?

**Comment by mattias-p** [comment]
Here's a good level for testing this: seed = 1468091799 tier = 2
There are bats and low walls in the room to the east.
