### ISSUE TITLE
Ease Agahnim difficulty scaling

### ISSUE THREAD

**Issue by sandstrand** [Legofarmen/tunics#8]
Agahnim appears to be to challenging for the first tier. The different metrics could be tier-dependent.

Tweak Agahnim behaviours depending on tier:
- Blue fireballs
- Number of fireballs on low health
- Number of fireball bounces
- Immunity to sword attack

**Comment by mattias-p** [comment]
How much damage should the sword and fireball do relative to eachother? How about other weapons?
