### ISSUE TITLE
Solarus 1.5

### ISSUE THREAD

**Issue by mattias-p** [Legofarmen/tunics#85]
Solarus 1.5 has been released. We should migrate to it.
Fixes #73.

**Comment by christopho** [comment]
You guys should get great performance improvements with 1.5. Solarus now much better handles maps with lots of dynamic entities.

**Comment by mattias-p** [comment]
@christopho I think that's very cool! Have you made any benchmarks? Or do you have ideas on how they should be done?
The only performance problem I've noticed on my machine is when there are too many enemies. I guess some enemy scripts might be heavier than others, though I have no particular suspects.
