### ISSUE TITLE
Installation instructions for OSX 1.5

### ISSUE THREAD

**Issue by sandstrand** [Legofarmen/tunics#88]
Test and reimplement installation instructions from 0.1

**Comment by sandstrand** [comment]
Still no clear solution to this. Disclaimer from 1.4 remains.

**Comment by mattias-p** [comment]
We still want this done. It's better to postpone the issue than to close it. Can you describe what problems you had with the instruction from 0.1?

**Comment by sandstrand** [comment]
You should be able to play this in several ways:
- Place the quest data folder in the app bundle (Solarus.app/Contents/Resources/), which work for 1.3 but not since.
- Place the quest data folder in the same folder as the application
- With 1.5 there is also a "wizard" for adding quests to play with Solarus.

None of these approaches work.

Error output is scarse, if I try to run the application within the Solarus.app i get the following error:
_This application failed to start because it could not find or load the Qt platform plugin "cocoa._

Launching with the wizard generates the following error:
_Error: In on_started: [string "lib/zentropy.lua"]:63: attempt to index a nil value_

None of these might help though, since if I launch the application within the Solarus-run app via command line: $BUNDLE_FOLDER/Solarus.app/Contents/Resources/solarus and if the quest data folder is in the bundle or in the same folder as the bundle, or if specifying path to quest data, it works without errors.

I do not think command line instructions are good enough.
