### ISSUE TITLE
Add help screen to game menu

### ISSUE THREAD

**Issue by sandstrand** [Legofarmen/tunics#9]
There is a help/controls png but it is not shown anywhere,
- Add a "help" or "about" menu item to game_menu. Choosing the menu item should display the control image.

**Comment by mattias-p** [comment]
I made a pull request for the controls screen.

Do you think we should hint about the F5, Alt+Enter and Alt+F4 as well?

**Comment by sandstrand** [comment]
We could, but it's getting cramped. I would like to split it in two screens/menus. Pressing action button should toggle between them. Sound good?

**Comment by mattias-p** [comment]
Sure! Could you look into the possibility of aligning the key column while you're at it?
